"""Add evaluations table

Revision ID: 18137670d0e3
Revises: cf5b58697b7a
Create Date: 2025-12-31 07:18:23.501109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18137670d0e3'
down_revision: Union[str, Sequence[str], None] = 'cf5b58697b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if evaluations table exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'evaluations' not in inspector.get_table_names():
        op.create_table('evaluations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('match_score', sa.Float(), nullable=False),
        sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_evaluations_candidate_id'), 'evaluations', ['candidate_id'], unique=True)
        op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
        op.create_index(op.f('ix_evaluations_match_score'), 'evaluations', ['match_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_match_score'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_candidate_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
