"""Add phone and location to candidates

Revision ID: 568feecd8fee
Revises: 18137670d0e3
Create Date: 2025-12-31 22:33:04.662636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568feecd8fee'
down_revision: Union[str, Sequence[str], None] = '18137670d0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('candidates')]

    if 'phone' not in columns:
        op.add_column('candidates', sa.Column('phone', sa.String(), nullable=True))
    if 'location' not in columns:
        op.add_column('candidates', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'location')
    op.drop_column('candidates', 'phone')
    # ### end Alembic commands ###
