"""Add candidates table

Revision ID: cf5b58697b7a
Revises: f93f4b3e658f
Create Date: 2025-12-31 06:26:49.527257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf5b58697b7a'
down_revision: Union[str, Sequence[str], None] = 'f93f4b3e658f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Add candidates table only."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type if it doesn't exist
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'candidatestatus'"
    )).fetchone()

    if not result:
        # ENUM doesn't exist, create it
        candidatestatus_enum = postgresql.ENUM('UPLOADED', 'PROCESSING', 'PARSED', 'SCORED', 'FAILED', name='candidatestatus')
        candidatestatus_enum.create(conn)

    # Jobs table already exists, only create candidates table if it doesn't exist
    inspector = sa.inspect(conn)
    if 'candidates' not in inspector.get_table_names():
        op.create_table('candidates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('resume_text', sa.Text(), nullable=True),
        sa.Column('anonymized_text', sa.Text(), nullable=True),
        sa.Column('status', postgresql.ENUM('UPLOADED', 'PROCESSING', 'PARSED', 'SCORED', 'FAILED', name='candidatestatus', create_type=False), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
        op.create_index(op.f('ix_candidates_job_id'), 'candidates', ['job_id'], unique=False)
        op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Remove candidates table only."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_job_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
