"""add_url_fields_to_candidates

Revision ID: d895320e817f
Revises: 568feecd8fee
Create Date: 2025-12-31 23:59:23.515261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd895320e817f'
down_revision: Union[str, Sequence[str], None] = '568feecd8fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('candidates')]

    if 'linkedin_url' not in columns:
        op.add_column('candidates', sa.Column('linkedin_url', sa.String(), nullable=True))
    if 'github_url' not in columns:
        op.add_column('candidates', sa.Column('github_url', sa.String(), nullable=True))
    if 'portfolio_url' not in columns:
        op.add_column('candidates', sa.Column('portfolio_url', sa.String(), nullable=True))
    if 'other_urls' not in columns:
        op.add_column('candidates', sa.Column('other_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'other_urls')
    op.drop_column('candidates', 'portfolio_url')
    op.drop_column('candidates', 'github_url')
    op.drop_column('candidates', 'linkedin_url')
    # ### end Alembic commands ###
